#!/bin/bash

pkg update
pkg install git clang -y

# Clone
git clone https://github.com/xiv3r/dhcp-starvation.git
cd dhcp-starvation

# Compile
g++ starv.cpp -o starv

# Prompt
echo " "
echo " "
echo "Installed Successfully...!"
echo " "
echo " "
cat << EOF
Launch Attack options;
Run with Interface: ./starv -i wlan0
Run in all Interfaces: ./starv
EOF
